$(document).ready(function(){
    		$("#bu1,#bu2,#bu3").hover(function(){
    				$(this).removeClass("toolbutton").addClass("toolbuttonhover");
        		},function(){
    				$(this).removeClass("toolbuttonhover").addClass("toolbutton");
        		});
            $("#bu4,#bu5").hover(function(){
                    $(this).removeClass("toolbutton-sign").addClass("toolbutton-signonhover");
                },function(){
                    $(this).removeClass("toolbutton-signonhover").addClass("toolbutton-sign");
                });
    		$("#search").hover(function(){
    				$(this).removeClass("searchbutton").addClass("searchhover");
        		},function(){
    				$(this).removeClass("searchhover").addClass("searchbutton");
        		});
});